[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/out"
  functions = "frontend/netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  directory = "frontend/netlify/functions"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs" 