[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/out"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs" 